#!/usr/bin/env python

Import('env')

env.ecs_sources = []

env.add_source_files(env.ecs_sources, "*.cpp")

SConscript('main/SCsub')

lib = env.add_library("ecs", env.ecs_sources)
env.Prepend(LIBS=[lib])

Export('env')
