#!/usr/bin/env python

Import('env')

env.ecs_sources = []

env.add_source_files(env.ecs_sources, "*.cpp")

SConscript('main/SCsub')
SConscript('resources/SCsub')
SConscript('components/SCsub')
SConscript('systems/SCsub')

ecs_env = env.Clone()
ecs_env.Append(CCFLAGS=['-std=c++11'])

lib = ecs_env.add_library("ecs", env.ecs_sources)
env.Prepend(LIBS=[lib])

Export('env')
